sudo: required
services:
  - docker
os:
  - linux
env:
  global:
    - DOCKER_IMAGE_NAME="containerd"
    - DOCKER_HUB_ORG="hamdiranu"
before_install:
  - openssl aes-256-cbc -K $encrypted_1614db0d6e9e_key -iv $encrypted_1614db0d6e9e_iv -in deploy_rsa.enc -out deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - chmod 600 deploy_rsa
  - ssh-add deploy_rsa
  - docker login -u "${DOCKER_USERNAME}" -p "${DOCKER_PASSWORD}"
script:
  - sudo chmod +x deploy.sh
  - sudo chmod 600 deploy_rsa
after_script:
  # - sed -i -e 's|FLASK_ENV_LOCAL|'"${FLASK_ENV_TRAVIS}"'|g' ./Dockerfile
  # - sed -i -e 's|THIS_U_NAME_LOCAL|'"${THIS_U_NAME_TRAVIS}"'|g' ./Dockerfile
  # - sed -i -e 's|THIS_PASSWORD_LOCAL|'"${THIS_PASSWORD_TRAVIS}"'|g' ./Dockerfile
  # - sed -i -e 's|THIS_ENDPOINT_LOCAL|'"${THIS_ENDPOINT_TRAVIS}"'|g' ./Dockerfile
  # - sed -i -e 's|THIS_DB_TEST_LOCAL|'"${THIS_DB_TEST_TRAVIS}"'|g' ./Dockerfile
  # - sed -i -e 's|THIS_DB_DEV_LOCAL|'"${THIS_DB_DEV_TRAVIS}"'|g' ./Dockerfile
  - docker build -t ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} .
  - docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID}
  - docker tag ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:backend-${TRAVIS_BUILD_ID} ${DOCKER_USERNAME}/${DOCKER_IMAGE_NAME}:be2
  - docker push ${DOCKER_HUB_ORG}/${DOCKER_IMAGE_NAME}:be2
  - ssh-keyscan -H $SSH_IP >> ~/.ssh/known_hosts
  - ssh -v -i deploy_rsa $SSH_USER@$SSH_IP DIR=$ROOT_DIR  'bash -s' < deploy.sh
