"""empty message

Revision ID: 26168d030e9d
Revises: 68e243f0b651
Create Date: 2020-01-03 17:10:03.330250

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26168d030e9d'
down_revision = '68e243f0b651'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('first_name', sa.String(length=30), nullable=False))
    op.add_column('User', sa.Column('last_name', sa.String(length=30), nullable=False))
    op.drop_column('User', 'name')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('User', sa.Column('name', mysql.VARCHAR(length=30), nullable=False))
    op.drop_column('User', 'last_name')
    op.drop_column('User', 'first_name')
    # ### end Alembic commands ###
